object Form1: TForm1
  Left = 192
  Top = 103
  Width = 783
  Height = 540
  Caption = 'Form1'
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  OldCreateOrder = False
  OnCreate = FormCreate
  PixelsPerInch = 96
  TextHeight = 13
  object DBGrid1: TDBGrid
    Left = 0
    Top = 0
    Width = 775
    Height = 472
    Align = alClient
    DataSource = DataSource1
    TabOrder = 0
    TitleFont.Charset = DEFAULT_CHARSET
    TitleFont.Color = clWindowText
    TitleFont.Height = -11
    TitleFont.Name = 'MS Sans Serif'
    TitleFont.Style = []
  end
  object Panel1: TPanel
    Left = 0
    Top = 472
    Width = 775
    Height = 41
    Align = alBottom
    TabOrder = 1
    object DBNavigator1: TDBNavigator
      Left = 16
      Top = 8
      Width = 240
      Height = 25
      DataSource = DataSource1
      TabOrder = 0
    end
    object Button1: TButton
      Left = 272
      Top = 8
      Width = 75
      Height = 25
      Caption = 'Restructure'
      TabOrder = 1
      OnClick = Button1Click
    end
    object Button2: TButton
      Left = 368
      Top = 8
      Width = 75
      Height = 25
      Caption = 'Close'
      TabOrder = 2
      OnClick = Button2Click
    end
  end
  object ACRDatabase1: TACRDatabase
    FormatVersion = 5.4
    DatabaseName = 'AccuracerDB_631452722-3988'
    InMemory = False
    SessionName = 'Default'
    DatabaseFileNameAnsi = 'test.adb'
    DatabaseFileName = 'test.adb'
    Exclusive = False
    BackupParams.CompressionAlgorithm = caNone
    BackupParams.CompressionMode = 1
    BackupParams.CryptoParams.CryptoAlgorithm = craNone
    BackupParams.CryptoParams.CryptoMode = acmCTS
    BackupParams.CryptoParams.KeySize = 56
    BackupParams.CryptoParams.Password = 'ACRpassword'
    BackupParams.CryptoParams.UseInitVector = False
    BackupParams.CryptoParams.InitVectorSize = 0
    BackupParams.BlockSize = 102400
    ConnectionParams.RemoteHost = '127.0.0.1'
    ConnectionParams.RemotePort = 12007
    ConnectionParams.LocalPort = 0
    ConnectionParams.DatabaseName = 'DBDemos'
    ConnectionParams.CompressionAlgorithm = caNone
    ConnectionParams.CompressionMode = 0
    ConnectionParams.CryptoParams.CryptoAlgorithm = craNone
    ConnectionParams.CryptoParams.CryptoMode = acmCTS
    ConnectionParams.CryptoParams.KeySize = 56
    ConnectionParams.CryptoParams.Password = 'ACRpassword'
    ConnectionParams.CryptoParams.UseInitVector = False
    ConnectionParams.CryptoParams.InitVectorSize = 0
    ConnectionParams.ServerID = 0
    ConnectionParams.NetworkSettings.PacketSize = 1492
    ConnectionParams.NetworkSettings.MaxThreadCount = 2147483647
    ConnectionParams.NetworkSettings.ConnectionParamsTunning = False
    ConnectionParams.NetworkSettings.TestPacketCount = 8
    ConnectionParams.NetworkSettings.DisconnectRetryCount = 12
    ConnectionParams.NetworkSettings.DisconnectDelay = 300
    ConnectionParams.NetworkSettings.CommandRetryCount = 5
    ConnectionParams.NetworkSettings.ReceiveTimeOut = 60000
    ConnectionParams.NetworkSettings.ReceiveSleep = 1
    ConnectionParams.NetworkSettings.MinSendTimeOut = 30000
    ConnectionParams.NetworkSettings.SendTimeOut = 300000
    ConnectionParams.NetworkSettings.WaitForSendSleep = 0
    ConnectionParams.NetworkSettings.ResendDelay = 300
    ConnectionParams.NetworkSettings.RequestDelay = 300
    ConnectionParams.NetworkSettings.WaitForTimeOut = 120000
    ConnectionParams.NetworkSettings.ThreadsTerminateDelay = 30000
    ConnectionParams.NetworkSettings.StartReceiveTimeOut = 30000
    ConnectionParams.NetworkSettings.RestoreDefaultSettings = ACRLocal
    ConnectionParams.NetworkSettings.ConnectRetryCount = 30
    ConnectionParams.NetworkSettings.ConnectDelay = 1000
    ConnectionParams.NetworkSettings.UseServerSettings = False
    ConnectionParams.MinCacheSize = 1457
    ConnectionParams.MaxCacheSize = 1048576
    LockParams.Delay = 1
    LockParams.RetryCount = 1000
    Options.MaxSessionCount = 2
    Options.PageSize = 4096
    Options.ExtentPageCount = 8
    Options.RandomSearchRetryCount = 10
    CryptoParams.CryptoAlgorithm = craNone
    CryptoParams.CryptoMode = acmCTS
    CryptoParams.KeySize = 56
    CryptoParams.Password = 'ACRpassword'
    CryptoParams.UseInitVector = False
    CryptoParams.InitVectorSize = 0
    Left = 72
    Top = 144
  end
  object ACRTable1: TACRTable
    CurrentVersion = '5.40 '
    InMemory = False
    DatabaseName = 'AccuracerDB_631452722-3988'
    ReadOnly = False
    TableName = 'test'
    Exclusive = False
    MemoryTableAllocBy = 1000
    Left = 72
    Top = 208
  end
  object DataSource1: TDataSource
    DataSet = ACRTable1
    Left = 64
    Top = 272
  end
end
