DROP TABLE Defaults CASCADE;
CREATE TABLE Defaults (
	ConsultantId INTEGER,
	ConsultantName CHAR (65),
	ConsultantAddress CHAR (78),
	Corrosion FLOAT,
	Metric_Corrosion FLOAT,
	DesignTemp FLOAT,
	Metric_DesignTemp FLOAT,
	ExternalTempEnglish FLOAT,
	ExternalTempMetric FLOAT,
	ExternalPressure FLOAT,
	MetricExternalPressure FLOAT,
	Design_Min_Temp FLOAT,
	Metric_Design_Min_Temp FLOAT,
	TorisDish FLOAT,
	FixedDish FLOAT,
	Metric_FixedDish FLOAT,
	TorisKnuckle FLOAT,
	Angle_a FLOAT,
	StraightFlange FLOAT,
	Metric_StraightFlange FLOAT,
	FixedThinOut FLOAT,
	Metric_FixedThinOut FLOAT,
	ExternalProjection FLOAT,
	Metric_ExternalProjection FLOAT,
	GutterWidth FLOAT,
	TopMargin FLOAT,
	BottomMargin FLOAT,
	RightMargin FLOAT,
	LeftMargin FLOAT,
	ConcreteStrength FLOAT,
	MetricConcreteStrength FLOAT,
	ConcreteFactor FLOAT,
	K_Braced FLOAT,
	K_Unbraced FLOAT,
	BgRed FLOAT,
	BgGreen FLOAT,
	BgBlue FLOAT,
	DirectLightIntensity FLOAT,
	AmbientLightIntensity FLOAT,
	Min_Thickness INTEGER,
	Metric_Min_Thickness INTEGER,
	Print_EFE INTEGER,
	RingStiffenerType INTEGER,
	Radiographed INTEGER,
	Use_FullVacuum INTEGER,
	NozConfig INTEGER,
	PrintStrengths INTEGER,
	TitleFontSize INTEGER,
	HeaderFontSize INTEGER,
	BodyFontSize INTEGER,
	MarginsMeasuredAs INTEGER,
	RenderQuality INTEGER,
	RotationSensitivity INTEGER,
	Resolution3D INTEGER,
	ZoomSensitivity INTEGER,
	StartReferencePointFrom INTEGER,
	VesselType INTEGER,
	DrawingSize INTEGER,
	ApplyForce INTEGER,
	SupportType INTEGER,
	IncreaseBSAllowStresses INTEGER,
	ANSIFlangeType CHAR (20),
	ANSIFlangeMatlGrp CHAR (10),
	ANSIFlangeMatl CHAR (22),
	TitleSign1 CHAR (35),
	TitleSign2 CHAR (35),
	TitleSign3 CHAR (35),
	TitleSign4 CHAR (35),
	NameSign1 CHAR (35),
	NameSign2 CHAR (35),
	NameSign3 CHAR (35),
	NameSign4 CHAR (35),
	ShellMatl CHAR (25),
	ShellMatlCondition CHAR (15),
	RingStiffenerMatl CHAR (25),
	RingStiffenerMatlCond CHAR (15),
	HeadMatl CHAR (25),
	HeadMatlCondition CHAR (15),
	HeadMinThicknessLbl CHAR (20),
	NozMatl CHAR (25),
	NozMatlCondition CHAR (15),
	ReinfMatl CHAR (25),
	ReinfMatlCondition CHAR (15),
	FlangeMaterial CHAR (25),
	FlangeMatlCondition CHAR (15),
	FlangeGasketMaterial CHAR (45),
	FlangeGasketType CHAR (15),
	FlangeBoltMaterial CHAR (25),
	FlangeBoltMatlCondition CHAR (15),
	TubeMaterial CHAR (25),
	TubeMatlCondition CHAR (15),
	TubeSheetMaterial CHAR (25),
	TubeSheetMatlCondition CHAR (15),
	BoltMaterial CHAR (25),
	BoltMatlCondition CHAR (15),
	SupportMatl CHAR (25),
	SupportMatlCondition CHAR (15),
	LegMatl CHAR (25),
	LegMatlCondition CHAR (15),
	Notes1 CHAR (75),
	Notes2 CHAR (75),
	Notes3 CHAR (75),
	Notes4 CHAR (75),
	Notes5 CHAR (75),
	TitleFont CHAR (35),
	HeaderFont CHAR (35),
	BodyFont CHAR (35),
	SystemOfUnits INTEGER,
	ID_or_OD INTEGER,
	T_or_P INTEGER,
	DisplayJobNoLabelAs CHAR (17),
	PhonePictureMask CHAR (14),
	ShowCountry LOGICAL,
	CopyCustInfoToLoc LOGICAL,
	AutoEnterDesc LOGICAL,
	Ask_Cast LOGICAL,
	Skip_Factor_A LOGICAL,
	Skip_Factor_B LOGICAL,
	Interpolate LOGICAL,
	PrintExtLoadsWarning LOGICAL,
	PrintCover LOGICAL,
	Print_1st_Sign LOGICAL,
	Print_2nd_Sign LOGICAL,
	Print_3rd_Sign LOGICAL,
	Print_4th_Sign LOGICAL,
	Print_NB_Number LOGICAL,
	Display_ASME_Stamped LOGICAL,
	BlankOut_ASME_Info LOGICAL,
	DefaultPreviewFullScreen LOGICAL,
	IncludeMAWPCalcsOnReports LOGICAL,
	ShowPageNumbers LOGICAL,
	EnterTorisAsPct LOGICAL,
	Print_ASME_on_Toris_Heads LOGICAL,
	Interpolate_Factor_k LOGICAL,
	Interpolate_Factor_KO LOGICAL,
	UseThinOutTable LOGICAL,
	ShowMinThickAfterForming LOGICAL,
	AddPlate LOGICAL,
	CalcReinf_If_Meets_UG36 LOGICAL,
	Nozzle_Limit_MAWP LOGICAL,
	Use_Excess_Thickness LOGICAL,
	ShowRigidityIndex LOGICAL,
	UseBoxes LOGICAL,
	BoldCompanyName LOGICAL,
	BoldCustomerName LOGICAL,
	PrintCustLocOnCoverPage LOGICAL,
	PrintProjectDesc LOGICAL,
	UseCorrodedWeight LOGICAL,
	UseTowerHigherWindSeismic LOGICAL,
	UseZickHigherWindSeismic LOGICAL,
	UseZickEffShellWidth LOGICAL,
	UseHigherS3Allowable LOGICAL,
	UseHigherBucklingAllow LOGICAL,
	ApplyUBC_CdivRw_Limit LOGICAL,
	SlidingSaddleSupLongLoads LOGICAL,
	CalculateSkirtStress LOGICAL,
	ShowNozzleImageOnReport LOGICAL,
	DrawRingOfHoles LOGICAL,
	HideNoAttachWarn LOGICAL,
	TableVersion INTEGER,
	ConsultantAddress2 CHAR (35),
	ConsultantCity CHAR (35),
	ConsultantState CHAR (25),
	ConsultantZipCode CHAR (10),
	ConsultantCountry CHAR (20),
	CellShadingOff LOGICAL,
	LockWmToMinimum LOGICAL,
	MatlDesc_UseSpec LOGICAL,
	MatlDesc_UseTypeGrade LOGICAL,
	MatlDesc_UseUNSNo LOGICAL,
	MatlCond_UseClass LOGICAL,
	MatlCond_UseSizeThick LOGICAL,
	Matl_SA516ToNormalized LOGICAL,
	WeldDetailRequirements CHAR (30),
	Version201020 LOGICAL,
PRIMARY KEY Defaults (ConsultantID)
);
INSERT INTO Defaults VALUES (
	1,
	'Pyramid Co.',
	'100 NW 5th St.   Pyramid City, Missouri  55555',
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0.1,
	0.35,
	0.35,
	0.35,
	0.35,
	3000,
	20,
	0.3,
	1,
	1.5,
	203,
	156,
	156,
	0.800000011920929,
	0.100000001490116,
	0,
	0,
	0,
	0,
	1,
	0,
	1,
	1,
	10,
	9,
	9,
	0,
	-1,
	5,
	2,
	5,
	0,
	0,
	2,
	1,
	7,
	0,
	'SO',
	'1.1',
	'SA-105 ',
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	'SA-516 Gr 70',
	NULL,
	'SA-36',
	NULL,
	'SA-516 Gr 70',
	NULL,
	'Minimum Thickness',
	'SA-106 Gr B',
	NULL,
	NULL,
	NULL,
	'SA-516 Gr 70',
	NULL,
	'Asbestos with suitable binder',
	'1/16 in. thick',
	'SA-36',
	NULL,
	'SA-179',
	NULL,
	'SA-516 Gr 70',
	NULL,
	'SA-36',
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	'Arial',
	'Arial',
	'Arial',
	0,
	0,
	0,
	'Job No:',
	'(999) 999-9999',
	False,
	True,
	True,
	True,
	True,
	True,
	True,
	True,
	True,
	True,
	False,
	False,
	False,
	True,
	True,
	False,
	True,
	False,
	True,
	True,
	True,
	True,
	True,
	True,
	True,
	False,
	False,
	True,
	True,
	True,
	True,
	True,
	True,
	True,
	True,
	False,
	False,
	False,
	False,
	False,
	False,
	True,
	True,
	False,
	True,
	True,
	True,
	20100200,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	True,
	True,
	True,
	True,
	False,
	True,
	False,
	True,
	'Corroded',
	NULL
);
