[Reg_Namespace]
;<nsName>|<nsColfile>|<nsDesc>
EasyTable_Reference|TetRef.hxc|EasyTable Component Reference - http://www.aidaim.com

[Reg_Title]
;<nsName>|<TitleID>|<LangId>|<HxS_HelpFile>|<HxI_IndexFile>|<HxQ_QueryFile>|<HxR_AttrQueryFile>|<HxsMediaLoc>|<HxqMediaLoc>|<HxrMediaLoc>|<SampleMediaLoc>
EasyTable_Reference|EasyTable_Reference|1033|TetRef.hxs|TetRef.hxs||||||

[Reg_Plugin]
;<nsName_Parent>|<HxT_Parent>|<nsName_Child>|<HxT_Child>|<HxA_Child>
Borland.BDS3||EasyTable_Reference|TetRef.hxt|
codegear.rs2007||EasyTable_Reference|TetRef.hxt|
embarcadero.rs2007||EasyTable_Reference|TetRef.hxt|
embarcadero.rs2009||EasyTable_Reference|TetRef.hxt|
embarcadero.rs2010||EasyTable_Reference|TetRef.hxt|
embarcadero.rs2011||EasyTable_Reference|TetRef.hxt|
embarcadero.rs_xe||EasyTable_Reference|TetRef.hxt|

[Reg_Filter]
;<nsName>|<FilterName>|<FilterQueryStr>

;------- UnRegister -u switch

[UnReg_Namespace]
;<nsName>
EasyTable_Reference

[UnReg_Title]
;<nsName>|<TitleID>|<LangId>
EasyTable_Reference|EasyTable_Reference||

[UnReg_Plugin]
;<nsName_Parent>|<HxT_Parent>|<nsName_Child>|<HxT_Child>|<HxA_Child>
Borland.BDS3||EasyTable_Reference|TetRef.hxt|
codegear.rs2007||EasyTable_Reference|TetRef.hxt|
embarcadero.rs2007||EasyTable_Reference|TetRef.hxt|
embarcadero.rs2009||EasyTable_Reference|TetRef.hxt|
embarcadero.rs2010||EasyTable_Reference|TetRef.hxt|
embarcadero.rs2011||EasyTable_Reference|TetRef.hxt|
embarcadero.rs_xe||EasyTable_Reference|TetRef.hxt|

[UnReg_Filter]
;<nsName>|<FilterName>
