[Reg_Namespace]
;<nsName>|<nsColfile>|<nsDesc>
Accuracer_Reference|AccuracerRef.hxc|Accuracer Component Reference - http://www.aidaim.com

[Reg_Title]
;<nsName>|<TitleID>|<LangId>|<HxS_HelpFile>|<HxI_IndexFile>|<HxQ_QueryFile>|<HxR_AttrQueryFile>|<HxsMediaLoc>|<HxqMediaLoc>|<HxrMediaLoc>|<SampleMediaLoc>
Accuracer_Reference|Accuracer_Reference|1033|AccuracerRef.hxs|AccuracerRef.hxs||||||

[Reg_Plugin]
;<nsName_Parent>|<HxT_Parent>|<nsName_Child>|<HxT_Child>|<HxA_Child>
Borland.BDS3||Accuracer_Reference|AccuracerRef.hxt|
codegear.rs2007||Accuracer_Reference|AccuracerRef.hxt|
embarcadero.rs2007||Accuracer_Reference|AccuracerRef.hxt|
embarcadero.rs2009||Accuracer_Reference|AccuracerRef.hxt|
embarcadero.rs2010||Accuracer_Reference|AccuracerRef.hxt|
embarcadero.rs2011||Accuracer_Reference|AccuracerRef.hxt|
embarcadero.rs_xe||Accuracer_Reference|AccuracerRef.hxt|

[Reg_Filter]
;<nsName>|<FilterName>|<FilterQueryStr>

;------- UnRegister -u switch

[UnReg_Namespace]
;<nsName>
Accuracer_Reference

[UnReg_Title]
;<nsName>|<TitleID>|<LangId>
Accuracer_Reference|Accuracer_Reference||

[UnReg_Plugin]
;<nsName_Parent>|<HxT_Parent>|<nsName_Child>|<HxT_Child>|<HxA_Child>
Borland.BDS3||Accuracer_Reference|AccuracerRef.hxt|
codegear.rs2007||Accuracer_Reference|AccuracerRef.hxt|
embarcadero.rs2007||Accuracer_Reference|AccuracerRef.hxt|
embarcadero.rs2009||Accuracer_Reference|AccuracerRef.hxt|
embarcadero.rs2010||Accuracer_Reference|AccuracerRef.hxt|
embarcadero.rs2011||Accuracer_Reference|AccuracerRef.hxt|
embarcadero.rs_xe||Accuracer_Reference|AccuracerRef.hxt|

[UnReg_Filter]
;<nsName>|<FilterName>
