[Reg_Namespace]
;<nsName>|<nsColfile>|<nsDesc>
MsgCommunicator|MsgCommunicator.hxc|MsgCommunicator - http://www.aidaim.com

[Reg_Title]
;<nsName>|<TitleID>|<LangId>|<HxS_HelpFile>|<HxI_IndexFile>|<HxQ_QueryFile>|<HxR_AttrQueryFile>|<HxsMediaLoc>|<HxqMediaLoc>|<HxrMediaLoc>|<SampleMediaLoc>
MsgCommunicator|MsgCommunicator|1033|MsgCommunicator.hxs|MsgCommunicator.hxs||||||

[Reg_Plugin]
;<nsName_Parent>|<HxT_Parent>|<nsName_Child>|<HxT_Child>|<HxA_Child>
Borland.BDS3||MsgCommunicator|MsgCommunicator.hxt|
codegear.rs2007||MsgCommunicator|MsgCommunicator.hxt|
embarcadero.rs2007||MsgCommunicator|MsgCommunicator.hxt|
embarcadero.rs2009||MsgCommunicator|MsgCommunicator.hxt|
embarcadero.rs2010||MsgCommunicator|MsgCommunicator.hxt|
embarcadero.rs2011||MsgCommunicator|MsgCommunicator.hxt|
embarcadero.rs_xe||MsgCommunicator|MsgCommunicator.hxt|

[Reg_Filter]
;<nsName>|<FilterName>|<FilterQueryStr>

;------- UnRegister -u switch

[UnReg_Namespace]
;<nsName>
MsgCommunicator

[UnReg_Title]
;<nsName>|<TitleID>|<LangId>
MsgCommunicator|MsgCommunicator||

[UnReg_Plugin]
;<nsName_Parent>|<HxT_Parent>|<nsName_Child>|<HxT_Child>|<HxA_Child>
Borland.BDS3||MsgCommunicator|MsgCommunicator.hxt|
codegear.rs2007||MsgCommunicator|MsgCommunicator.hxt|
embarcadero.rs2007||MsgCommunicator|MsgCommunicator.hxt|
embarcadero.rs2009||MsgCommunicator|MsgCommunicator.hxt|
embarcadero.rs2010||MsgCommunicator|MsgCommunicator.hxt|
embarcadero.rs2011||MsgCommunicator|MsgCommunicator.hxt|
embarcadero.rs_xe||MsgCommunicator|MsgCommunicator.hxt|

[UnReg_Filter]
;<nsName>|<FilterName>
