SELECT FInteger,FString FROM JT1
 UNION ALL 
SELECT FInteger,FString FROM JT2
 UNION ALL
SELECT FInteger,FString FROM JT3;
#DBISAM
(SELECT FInteger,FString FROM JT1)
 UNION ALL
(SELECT FInteger,FString FROM JT2)
 UNION ALL
(SELECT FInteger,FString FROM JT3);