SELECT FInteger FROM JT1
 UNION ALL 
SELECT FInteger FROM JT2
 UNION ALL
SELECT FInteger FROM JT3;
#DBISAM
(SELECT FInteger FROM JT1)
 UNION ALL
(SELECT FInteger FROM JT2)
 UNION ALL
(SELECT FInteger FROM JT3);