#exec
DROP TABLE MEMORY TPERSON;
#exec
DROP TABLE MEMORY TPERSONRELATION;
#exec
CREATE TABLE MEMORY TPERSON (ID INTEGER, NAME STRING(50), AGE INTEGER);
#exec
CREATE TABLE MEMORY TPERSONRELATION (CHILDID INTEGER ,PARENTID INTEGER);
SELECT * FROM MEMORY TPERSON P1 
INNER JOIN MEMORY TPERSONRELATION PR ON P1.ID = PR.CHILDID 
INNER JOIN MEMORY TPERSON P2 ON P2.ID = PR.PARENTID
#DBISAM
#exec
CREATE TABLE "\MEMORY\TPERSON1" (ID INTEGER, NAME CHAR(50), AGE INTEGER);
#exec
CREATE TABLE "\MEMORY\TPERSONRELATION1" (CHILDID INTEGER ,PARENTID INTEGER);
SELECT * FROM "\MEMORY\TPERSON1" P1 
INNER JOIN "\MEMORY\TPERSONRELATION1" PR ON P1.ID = PR.CHILDID 
INNER JOIN "\MEMORY\TPERSON1" P2 ON P2.ID = PR.PARENTID
