#exec
DROP TABLE MEMORY Tmp;
#exec
CREATE TABLE MEMORY Tmp (dt DateTime);
#exec
INSERT INTO MEMORY Tmp VALUES(TODATE('01/01/2006','MM/DD/YYYY'));
#exec
INSERT INTO MEMORY Tmp VALUES(TODATE('02/01/2005','MM/DD/YYYY'));
#exec
INSERT INTO MEMORY Tmp VALUES(TODATE('03/01/2005','MM/DD/YYYY'));
#exec
INSERT INTO MEMORY Tmp VALUES(TODATE('04/01/2005','MM/DD/YYYY'));
#exec
INSERT INTO MEMORY Tmp VALUES(TODATE('05/01/2005','MM/DD/YYYY'));
#exec
INSERT INTO MEMORY Tmp VALUES(TODATE('06/01/2005','MM/DD/YYYY'));
#exec
INSERT INTO MEMORY Tmp VALUES(TODATE('07/01/2005','MM/DD/YYYY'));
#exec
INSERT INTO MEMORY Tmp VALUES(TODATE('08/01/2005','MM/DD/YYYY'));
#exec
INSERT INTO MEMORY Tmp VALUES(TODATE('09/01/2005','MM/DD/YYYY'));
#exec
INSERT INTO MEMORY Tmp VALUES(TODATE('10/01/2005','MM/DD/YYYY'));
#exec
INSERT INTO MEMORY Tmp VALUES(TODATE('12/01/2005','MM/DD/YYYY'));
#exec
INSERT INTO MEMORY Tmp VALUES(TODATE('12/01/2005','MM/DD/YYYY'));
select QUARTER(dt) f1 FROM MEMORY Tmp order by f1;
#dbisam 
#exec
DROP TABLE if exists "\MEMORY\Tmp";
#exec
CREATE TABLE "\MEMORY\Tmp" (f1 Integer);
#exec
INSERT INTO "\MEMORY\Tmp" VALUES(1);
#exec
INSERT INTO "\MEMORY\Tmp" VALUES(1);
#exec
INSERT INTO "\MEMORY\Tmp" VALUES(1);
#exec
INSERT INTO "\MEMORY\Tmp" VALUES(2);
#exec
INSERT INTO "\MEMORY\Tmp" VALUES(2);
#exec
INSERT INTO "\MEMORY\Tmp" VALUES(2);
#exec
INSERT INTO "\MEMORY\Tmp" VALUES(3);
#exec
INSERT INTO "\MEMORY\Tmp" VALUES(3);
#exec
INSERT INTO "\MEMORY\Tmp" VALUES(3);
#exec
INSERT INTO "\MEMORY\Tmp" VALUES(4);
#exec
INSERT INTO "\MEMORY\Tmp" VALUES(4);
#exec
INSERT INTO "\MEMORY\Tmp" VALUES(4);
SELECT f1 FROM "\MEMORY\Tmp" order by f1;