DROP TABLE MEMORY Test;
CREATE TABLE MEMORY Test (
	id  AUTOINC (AUTOINC INITIALVALUE 0 INCREMENT 1 NOMINVALUE NOMAXVALUE NOCYCLED),
	str CHAR (100) DEFAULT 'aaa',
	num SIGNEDINT32);
INSERT INTO MEMORY Test VALUES (
	1,
	'aaa',
	5
);
